export { scanProject } from './scanner.js'
export { buildNavGraph } from './nav-graph.js'
export type { NavGraphResult } from './nav-graph.js'
export { backupRunContext } from './run-context-backup.js'
export { buildAppContextSummary, enforceTokenCap } from './token-cap.js'
export type { FileCategory, InventoryEntry, NavNode, AppContext } from './types.js'
export { planModifications } from './modification-planner.js'
export type { ModificationPlan, ModificationItem, ModificationChangeType } from '@appifex/core'
export { diffScreenInventory } from './modified-screens.js'
export { diffDesignTokens } from './design-delta.js'
