export { scanProject } from './scanner.js'
export { buildNavGraph } from './nav-graph.js'
export type { NavGraphResult } from './nav-graph.js'
export { backupRunContext } from './run-context-backup.js'
export { buildAppContextSummary, enforceTokenCap } from './token-cap.js'
export type { FileCategory, InventoryEntry, NavNode, AppContext } from './types.js'
export { planModifications } from './modification-planner.js'
export type { ModificationPlan, ModificationItem, ModificationChangeType } from '@appifex/core'
export { diffScreenInventory } from './modified-screens.js'
export { diffDesignTokens } from './design-delta.js'
// Phase 6 (VAL-02 D-10): fix-context ranker — consumed by @appifex/fix
export { rankFixContext, CHARS_PER_TOKEN, FIX_CONTEXT_BUDGET_RATIO } from './fix-context-ranker.js'
export type { RankFixContextInput, RankFixContextResult } from './fix-context-ranker.js'
