import type { Runner } from '@appifex/core'
import { GitClient, type GitConfig } from './git-client.js'
import { createPullRequest, mergePullRequest, createRepo, type PullRequestResult, type MergeMethod } from './github.js'

export interface DeliverOpts {
  projectDir: string
  commitMessage?: string
  branch?: string
  baseBranch?: string
  remote?: string
  remoteUrl?: string
  repoName?: string
  repoVisibility?: 'private' | 'public'
  git?: GitConfig
  repo?: { owner: string; repo: string }
  skipPr?: boolean
  skipPush?: boolean
  summary?: string
  autoMerge?: boolean
  mergeMethod?: MergeMethod
  deleteBranchOnMerge?: boolean
  allTestsGreen?: boolean
}

export interface DeliverResult {
  commitHash: string
  branch: string
  pushed: boolean
  pr?: PullRequestResult
  remoteUrl?: string
  repoCreated?: boolean
}

/**
 * Delivers generated code: git init/add/commit, push, and optionally create a PR.
 */
export async function deliver(runner: Runner, opts: DeliverOpts): Promise<DeliverResult> {
  const git = new GitClient(runner, opts.projectDir, opts.git)
  const remote = opts.remote ?? 'origin'
  const baseBranch = opts.baseBranch ?? 'main'

  // Ensure repo exists and identity is configured
  const wasNewRepo = await ensureRepo(git, baseBranch)

  // Stage and check for changes
  await git.addAll()
  if (!(await git.hasChanges())) {
    return noChangesResult(git, baseBranch)
  }

  // Resolve remote (reuse existing, or auto-create)
  const { remoteUrl, repoInfo, repoCreated } = opts.skipPush
    ? { remoteUrl: opts.remoteUrl, repoInfo: opts.repo ?? parseRepoFromUrl(opts.remoteUrl), repoCreated: false }
    : await resolveRemote(runner, git, remote, opts)

  // Determine if initial commit (empty remote → push to base branch directly)
  const isInitial = await isInitialCommit(git, wasNewRepo, repoCreated, opts.skipPush, remote, baseBranch, remoteUrl)
  const branchName = isInitial ? baseBranch : (opts.branch ?? `dtc/${Date.now()}`)
  if (!isInitial) await git.createBranch(branchName)

  // Commit and push
  const commitHash = await git.commit(opts.commitMessage ?? buildCommitMessage(opts.summary))
  let pushed = false
  if (!opts.skipPush) {
    await git.push(remote, branchName, true)
    pushed = true
  }

  // Create PR + auto-merge (only for non-initial commits)
  const pr = pushed && !isInitial && !opts.skipPr && repoInfo
    ? await createAndMergePr(runner, repoInfo, branchName, baseBranch, opts)
    : undefined

  return { commitHash, branch: branchName, pushed, pr, remoteUrl, repoCreated }
}

// ── Helpers ──

async function ensureRepo(git: GitClient, baseBranch: string): Promise<boolean> {
  const wasNew = !(await git.isRepo())
  if (wasNew) {
    await git.init()
    // Ensure we're on the target base branch regardless of git's default
    await git.createBranch(baseBranch)
  }
  // Always apply identity (handles existing repos without global git config)
  await git.ensureIdentity()
  return wasNew
}

async function noChangesResult(git: GitClient, baseBranch: string): Promise<DeliverResult> {
  const branch = await git.currentBranch() || baseBranch
  let hash = 'unknown'
  try { hash = (await git.log(1)).split(' ')[0] ?? 'unknown' } catch { /* no commits yet */ }
  return { commitHash: hash, branch, pushed: false }
}

async function resolveRemote(
  runner: Runner, git: GitClient, remote: string, opts: DeliverOpts,
): Promise<{ remoteUrl: string; repoInfo: { owner: string; repo: string } | undefined; repoCreated: boolean }> {
  let remoteUrl = opts.remoteUrl
  let repoInfo = opts.repo ?? parseRepoFromUrl(remoteUrl)
  let repoCreated = false

  // Check existing git remote
  if (!remoteUrl) {
    const existing = await git.getRemoteUrl(remote)
    if (existing) {
      remoteUrl = existing
      repoInfo = repoInfo ?? parseRepoFromUrl(existing)
    }
  }

  // Auto-create if still no remote
  if (!remoteUrl) {
    const { basename } = await import('node:path')
    const name = opts.repoName ?? basename(opts.projectDir)
    const created = await createRepo(runner, name, { private: opts.repoVisibility !== 'public', description: 'Generated by dtc pipeline' })
    remoteUrl = created.url
    repoInfo = { owner: created.owner, repo: created.repo }
    repoCreated = true
  }

  await git.addRemote(remote, remoteUrl)
  return { remoteUrl, repoInfo, repoCreated }
}

async function isInitialCommit(
  git: GitClient, wasNewRepo: boolean, repoCreated: boolean,
  skipPush: boolean | undefined, remote: string, baseBranch: string, remoteUrl?: string,
): Promise<boolean> {
  if (wasNewRepo || repoCreated) return true
  if (!skipPush && remoteUrl) {
    return !(await git.remoteBranchExists(remote, baseBranch))
  }
  return false
}

async function createAndMergePr(
  runner: Runner,
  repoInfo: { owner: string; repo: string },
  head: string, base: string, opts: DeliverOpts,
): Promise<PullRequestResult> {
  const body = buildPrBody(opts.summary, opts.autoMerge && opts.allTestsGreen)
  let pr = await createPullRequest(runner, {
    owner: repoInfo.owner, repo: repoInfo.repo,
    title: buildPrTitle(opts.summary), body, head, base,
  })

  if (opts.autoMerge && opts.allTestsGreen && pr) {
    await mergePullRequest(runner, {
      owner: repoInfo.owner, repo: repoInfo.repo,
      prNumber: pr.number, method: opts.mergeMethod ?? 'squash',
      deleteBranch: opts.deleteBranchOnMerge ?? true,
    })
    pr = { ...pr, merged: true, mergeMethod: opts.mergeMethod ?? 'squash' }
  }
  return pr
}

function buildCommitMessage(summary?: string): string {
  const headline = 'feat: generated code via dtc pipeline'
  return summary ? `${headline}\n\n${summary}` : headline
}

function buildPrTitle(summary?: string): string {
  if (!summary) return 'feat: generated code via dtc pipeline'
  const first = summary.split('\n')[0]!.trim()
  return first.length > 60 ? first.slice(0, 57) + '...' : first
}

function buildPrBody(summary?: string, willAutoMerge?: boolean): string {
  const parts = [
    '## Summary', summary ?? 'Code generated by the dtc (Design-to-Code) pipeline.', '',
    '## Pipeline', 'Generated via `dtc run` — design → spec → test-gen → codegen → build → validate → fix → deliver',
  ]
  if (willAutoMerge) parts.push('', '> Auto-merged: all tests passed.')
  parts.push('', 'Generated with [appifex-dtc](https://github.com/appifex-ai-org/appifex-dtc)')
  return parts.join('\n')
}

/** Extract owner/repo from a GitHub remote URL */
function parseRepoFromUrl(url?: string): { owner: string; repo: string } | undefined {
  if (!url) return undefined
  const https = url.match(/github\.com\/([^/]+)\/([^/.]+)/)
  if (https) return { owner: https[1]!, repo: https[2]! }
  const ssh = url.match(/github\.com:([^/]+)\/([^/.]+)/)
  if (ssh) return { owner: ssh[1]!, repo: ssh[2]! }
  return undefined
}
