export { createAgent, detectAgent } from './registry.js'
export type { DetectAgentOpts } from './registry.js'
export { buildAgentPrompt } from './prompt-builder.js'
export type { PromptBuilderOpts } from './prompt-builder.js'
export { ClaudeCodeAgent } from './adapters/claude.js'
export { CodexAgent } from './adapters/codex.js'
export { GeminiAgent } from './adapters/gemini.js'
export { createProgressParser } from './progress.js'
export type { ProgressParser } from './progress.js'
export type { AgentAdapter, AgentRunOpts, AgentResult, AgentType } from './types.js'
