/**
 * Maps Pencil.dev icon font names to SF Symbols.
 * Covers the most commonly used icons across Lucide, Material Symbols,
 * Feather, and Phosphor.
 *
 * All SF Symbol names target iOS 17+ (the DTC pipeline's minimum deployment target).
 * Some symbols like party.popper.fill, storefront.fill require iOS 17+.
 *
 * Format: { [family]: { [iconName]: sfSymbolName } }
 */
export const ICON_TO_SF_SYMBOL: Record<string, Record<string, string>> = {
  lucide: {
    home: 'house.fill',
    house: 'house.fill',
    search: 'magnifyingglass',
    settings: 'gearshape.fill',
    user: 'person.fill',
    'user-circle': 'person.circle.fill',
    'user-plus': 'person.badge.plus',
    users: 'person.2.fill',
    heart: 'heart.fill',
    star: 'star.fill',
    plus: 'plus',
    'plus-circle': 'plus.circle.fill',
    minus: 'minus',
    x: 'xmark',
    'x-circle': 'xmark.circle.fill',
    check: 'checkmark',
    'check-circle': 'checkmark.circle.fill',
    'circle-check': 'checkmark.circle.fill',
    'chevron-left': 'chevron.backward',
    'chevron-right': 'chevron.forward',
    'chevron-up': 'chevron.up',
    'chevron-down': 'chevron.down',
    'arrow-left': 'arrow.backward',
    'arrow-right': 'arrow.forward',
    'arrow-up': 'arrow.up',
    'arrow-down': 'arrow.down',
    bell: 'bell.fill',
    mail: 'envelope.fill',
    'message-circle': 'bubble.left.fill',
    phone: 'phone.fill',
    camera: 'camera.fill',
    image: 'photo.fill',
    edit: 'pencil',
    'pencil-line': 'pencil',
    trash: 'trash.fill',
    'trash-2': 'trash.fill',
    share: 'square.and.arrow.up',
    'share-2': 'square.and.arrow.up',
    download: 'arrow.down.circle.fill',
    upload: 'arrow.up.circle.fill',
    link: 'link',
    'external-link': 'arrow.up.right.square',
    eye: 'eye.fill',
    'eye-off': 'eye.slash.fill',
    lock: 'lock.fill',
    unlock: 'lock.open.fill',
    calendar: 'calendar',
    clock: 'clock.fill',
    'clock-3': 'clock.fill',
    'map-pin': 'mappin',
    navigation: 'location.fill',
    filter: 'line.3.horizontal.decrease',
    list: 'list.bullet',
    grid: 'square.grid.2x2.fill',
    menu: 'line.3.horizontal',
    'more-horizontal': 'ellipsis',
    'more-vertical': 'ellipsis',
    ellipsis: 'ellipsis',
    info: 'info.circle.fill',
    'alert-circle': 'exclamationmark.circle.fill',
    'alert-triangle': 'exclamationmark.triangle.fill',
    bookmark: 'bookmark.fill',
    tag: 'tag.fill',
    folder: 'folder.fill',
    file: 'doc.fill',
    'file-text': 'doc.text.fill',
    copy: 'doc.on.doc.fill',
    clipboard: 'clipboard.fill',
    'log-out': 'rectangle.portrait.and.arrow.right',
    'log-in': 'rectangle.portrait.and.arrow.forward',
    refresh: 'arrow.clockwise',
    'rotate-cw': 'arrow.clockwise',
    wifi: 'wifi',
    bluetooth: 'bluetooth',
    battery: 'battery.100',
    sun: 'sun.max.fill',
    moon: 'moon.fill',
    cloud: 'cloud.fill',
    zap: 'bolt.fill',
    'shopping-cart': 'cart.fill',
    'shopping-bag': 'bag.fill',
    gift: 'gift.fill',
    'credit-card': 'creditcard.fill',
    dollar: 'dollarsign.circle.fill',
    music: 'music.note',
    play: 'play.fill',
    pause: 'pause.fill',
    'skip-forward': 'forward.fill',
    'skip-back': 'backward.fill',
    volume: 'speaker.wave.2.fill',
    'volume-x': 'speaker.slash.fill',
    mic: 'mic.fill',
    'mic-off': 'mic.slash.fill',
    video: 'video.fill',
    'video-off': 'video.slash.fill',
    globe: 'globe',
    flag: 'flag.fill',
    award: 'rosette',
    trending: 'chart.line.uptrend.xyaxis',
    'trending-up': 'chart.line.uptrend.xyaxis',
    'bar-chart': 'chart.bar.fill',
    'pie-chart': 'chart.pie.fill',
    activity: 'waveform.path.ecg',
    thermometer: 'thermometer.medium',
    droplet: 'drop.fill',
    compass: 'safari.fill',
    'book-open': 'book.fill',
    cake: 'birthday.cake.fill',
    'party-popper': 'party.popper.fill',
    package: 'shippingbox.fill',
    store: 'storefront.fill',
    circle: 'circle',
    'circle-dot': 'circle.inset.filled',
    square: 'square',
    'help-circle': 'questionmark.circle.fill',
    layers: 'square.3.layers.3d',
    sliders: 'slider.horizontal.3',
    'thumbs-up': 'hand.thumbsup.fill',
    'thumbs-down': 'hand.thumbsdown.fill',
    send: 'paperplane.fill',
    inbox: 'tray.fill',
    archive: 'archivebox.fill',
    printer: 'printer.fill',
    save: 'square.and.arrow.down',
    'scan-line': 'barcode.viewfinder',
    qr: 'qrcode',
    map: 'map.fill',
    'message-square': 'bubble.left.fill',
    at: 'at',
    hash: 'number',
    percent: 'percent',
  },
  'Material Symbols Outlined': {
    home: 'house.fill',
    search: 'magnifyingglass',
    settings: 'gearshape.fill',
    person: 'person.fill',
    group: 'person.2.fill',
    favorite: 'heart.fill',
    star: 'star.fill',
    add: 'plus',
    close: 'xmark',
    check: 'checkmark',
    arrow_back: 'chevron.backward',
    arrow_forward: 'chevron.forward',
    arrow_upward: 'arrow.up',
    arrow_downward: 'arrow.down',
    notifications: 'bell.fill',
    email: 'envelope.fill',
    chat: 'bubble.left.fill',
    call: 'phone.fill',
    camera_alt: 'camera.fill',
    photo: 'photo.fill',
    edit: 'pencil',
    delete: 'trash.fill',
    share: 'square.and.arrow.up',
    visibility: 'eye.fill',
    visibility_off: 'eye.slash.fill',
    lock: 'lock.fill',
    calendar_today: 'calendar',
    schedule: 'clock.fill',
    location_on: 'mappin',
    filter_list: 'line.3.horizontal.decrease',
    menu: 'line.3.horizontal',
    more_vert: 'ellipsis',
    more_horiz: 'ellipsis',
    info: 'info.circle.fill',
    warning: 'exclamationmark.triangle.fill',
    bookmark: 'bookmark.fill',
    shopping_cart: 'cart.fill',
    file_copy: 'doc.on.doc.fill',
    folder: 'folder.fill',
    description: 'doc.text.fill',
    send: 'paperplane.fill',
    map: 'map.fill',
    download: 'arrow.down.circle.fill',
    upload: 'arrow.up.circle.fill',
    refresh: 'arrow.clockwise',
    play_arrow: 'play.fill',
    pause: 'pause.fill',
    skip_next: 'forward.fill',
    skip_previous: 'backward.fill',
    volume_up: 'speaker.wave.2.fill',
    volume_off: 'speaker.slash.fill',
    mic: 'mic.fill',
    mic_off: 'mic.slash.fill',
  },
  phosphor: {
    house: 'house.fill',
    'magnifying-glass': 'magnifyingglass',
    gear: 'gearshape.fill',
    user: 'person.fill',
    'users-three': 'person.2.fill',
    heart: 'heart.fill',
    star: 'star.fill',
    plus: 'plus',
    x: 'xmark',
    check: 'checkmark',
    'caret-left': 'chevron.backward',
    'caret-right': 'chevron.forward',
    'caret-up': 'chevron.up',
    'caret-down': 'chevron.down',
    bell: 'bell.fill',
    envelope: 'envelope.fill',
    'chat-circle': 'bubble.left.fill',
    phone: 'phone.fill',
    camera: 'camera.fill',
    image: 'photo.fill',
    pencil: 'pencil',
    trash: 'trash.fill',
    'share-network': 'square.and.arrow.up',
    eye: 'eye.fill',
    'eye-slash': 'eye.slash.fill',
    lock: 'lock.fill',
    calendar: 'calendar',
    clock: 'clock.fill',
    'map-pin': 'mappin',
    funnel: 'line.3.horizontal.decrease',
    list: 'list.bullet',
    'squares-four': 'square.grid.2x2.fill',
    'dots-three': 'ellipsis',
    info: 'info.circle.fill',
    warning: 'exclamationmark.triangle.fill',
    bookmark: 'bookmark.fill',
    'shopping-cart': 'cart.fill',
    globe: 'globe',
    'paper-plane': 'paperplane.fill',
  },
  // Feather uses the same icon names as Lucide
  feather: {},
  // Material Symbols Rounded and Sharp use the same names as Outlined
  'Material Symbols Rounded': {},
  'Material Symbols Sharp': {},
}

// Feather falls back to Lucide
ICON_TO_SF_SYMBOL.feather = ICON_TO_SF_SYMBOL.lucide
// Material variants share the same map
ICON_TO_SF_SYMBOL['Material Symbols Rounded'] = ICON_TO_SF_SYMBOL['Material Symbols Outlined']
ICON_TO_SF_SYMBOL['Material Symbols Sharp'] = ICON_TO_SF_SYMBOL['Material Symbols Outlined']

/**
 * Look up the SF Symbol name for a Pencil icon.
 * Returns the SF Symbol name, or the original icon name as fallback.
 */
export function toSfSymbol(family: string, name: string): string {
  const familyMap = ICON_TO_SF_SYMBOL[family]
  if (familyMap?.[name]) return familyMap[name]

  // Feather fallback to lucide (in case the alias wasn't applied)
  if (family === 'feather') {
    const lucide = ICON_TO_SF_SYMBOL.lucide
    if (lucide[name]) return lucide[name]
  }

  // Last resort: return icon name as-is (agent will interpret)
  return name
}
