import type { BaasProvider } from '@appifex/core'

interface GeneratedFile { path: string; content: string }

const FIREBASE_PLIST_STUB = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- PLACEHOLDER — Replace with real values from Firebase Console -->
    <key>API_KEY</key>            <string>REPLACE_WITH_REAL_API_KEY</string>
    <key>GCM_SENDER_ID</key>      <string>REPLACE_WITH_GCM_SENDER_ID</string>
    <key>BUNDLE_ID</key>          <string>REPLACE_WITH_BUNDLE_ID</string>
    <key>PROJECT_ID</key>         <string>REPLACE_WITH_PROJECT_ID</string>
    <key>STORAGE_BUCKET</key>     <string>REPLACE_WITH_STORAGE_BUCKET</string>
    <key>GOOGLE_APP_ID</key>      <string>REPLACE_WITH_GOOGLE_APP_ID</string>
</dict>
</plist>`

const SUPABASE_ENV_STUB = `# PLACEHOLDER — Replace with real values from Supabase Project Settings > API
SUPABASE_URL=https://placeholder.supabase.co
SUPABASE_ANON_KEY=placeholder-anon-key`

const GITIGNORE_ENTRIES = `# BaaS credentials (generated by DTC — replace placeholders before shipping)
GoogleService-Info.plist
google-services.json
.env
*.env.local`

export function generateConfigStubs(provider: BaasProvider): GeneratedFile[] {
  if (provider === 'mock') return []
  const files: GeneratedFile[] = []

  if (provider === 'firebase') {
    files.push({ path: 'GoogleService-Info.plist', content: FIREBASE_PLIST_STUB })
  } else {
    files.push({ path: '.env', content: SUPABASE_ENV_STUB })
  }

  files.push({ path: '.gitignore.baas', content: GITIGNORE_ENTRIES })

  return files
}

export function generateSkipTemplate(): GeneratedFile {
  return {
    path: 'baas-config.template',
    content: `# BaaS Configuration Template — generated by dtc setup
# Uncomment and fill in the provider you want to use.
# Once configured, re-run \`dtc setup\` or set config.baas.provider in your config.

# ── Firebase ──────────────────────────────────────────────────────────────────
# Drop GoogleService-Info.plist (iOS) or google-services.json (Android) into
# your project root. DTC will auto-detect Firebase on next run.
# Download from: Firebase Console > Project Settings > Your apps

# ── Supabase ─────────────────────────────────────────────────────────────────
# Set these environment variables (or add to .env):
# SUPABASE_URL=https://your-project.supabase.co
# SUPABASE_ANON_KEY=your-anon-key
# Find these at: Supabase Dashboard > Project Settings > API
`,
  }
}
