import { Eta } from 'eta'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { BaasProvider } from '@appifex/core'

interface GeneratedFile {
  path: string
  content: string
}

const __dirname = dirname(fileURLToPath(import.meta.url))

export function generateSdkInit(provider: BaasProvider): GeneratedFile {
  if (provider === 'mock') {
    return {
      path: 'Sources/AppEntry.swift',
      content:
        '// Generated by appifex-dtc — mock provider\n// Mock provider: no SDK initialization required\n',
    }
  }
  const eta = new Eta({ views: join(__dirname, 'templates', provider) })
  return {
    path: 'Sources/AppEntry.swift',
    content: eta.render('./app-entry.swift.eta', {}),
  }
}
